### ISSUE TITLE
Dúvida "Esquema e tabelas"

### ISSUE THREAD

**Issue by jlsilva01** [taylorteixeira/projeto-bd-odontologico#1]
@taylorteixeira os arquivos que estão neste diretório [https://github.com/taylorteixeira/projeto-bd-odontologico/blob/main/Esquema%20e%20Tabelas](https://github.com/taylorteixeira/projeto-bd-odontologico/blob/main/Esquema%20e%20Tabelas) é o script do modelo do dbdiagram.io, certo?

Para gerar os scripts de DDL vocês precisam exportar o modelo do dbdiagram.io para o tipo de banco de dados que vocês escolheram para guardar no GitHub.

**Comment by taylorteixeira** [comment]
Sim, esses são os arquivos do modelo do dbdiagram.io
