### ISSUE TITLE
Ideia de trigger

### ISSUE THREAD

**Issue by CauaLoch9860** [taylorteixeira/projeto-bd-odontologico#10]
Trigger para Atualização da Disponibilidade na Tabela Agendas

CREATE TRIGGER trg_AfterInsertConsulta_UpdateAgenda
ON Consultas
AFTER INSERT
AS
BEGIN
    -- Declaração de variáveis
    DECLARE @DentistaID INT, @DataHora DATETIME;
    
    -- Selecionar os dados da nova consulta inserida
    SELECT @DentistaID = i.DentistaID, 
           @DataHora = i.DataHora
    FROM Inserted i;

    -- Atualizar a disponibilidade do dentista para FALSE
    UPDATE Agendas
    SET Disponivel = 0
    WHERE DentistaID = @DentistaID AND DataHora = @DataHora;
END;
GO

**Comment by miguelfermo** [comment]
ok
