### ISSUE TITLE
Modificações finais

### ISSUE THREAD

**Issue by ribarski** [taylorteixeira/projeto-bd-odontologico#16]
Ao adicionar uma nova consulta informar 
paciente - ja existe no banco
medico - ja existe no banco
data 
tratamento (essa coluna deve ser a coluna descrição da tabela tratamento que possui as informações do tempo do procedimento) 
- procedure -> adiciona uma nova consulta a partir do nome do paciente e medico,
dispara a trigger que faz o calculo da duração da consulta para adicionar na tabela AGENDA a data inicio e data final.

**Comment by ribarski** [comment]
Essa função vai ser alterada depois pra puxar o tratamento no lugar do motivo (só trocar o nome)
CREATE FUNCTION ConsultasComNomes()
RETURNS TABLE
AS
RETURN
(
    SELECT 
        C.ConsultaID,
        C.PacienteID,
        P.Nome AS NomePaciente,
        C.DentistaID,
        D.Nome AS NomeDentista,
        dbo.FormatarDataHoraBrasileira(C.DataHora) AS DataHoraFormatada,
        C.Motivo
    FROM Consultas C
    INNER JOIN Pacientes P ON C.PacienteID = P.PacienteID
    INNER JOIN Dentistas D ON C.DentistaID = D.DentistaID
);
GO

**Comment by AlexandreDestro** [comment]
conferir os usos de índex nas consultas sobre as perguntas de negócio

**Comment by miguelfermo** [comment]
verificar erros:

'TABELA CONSULTAS.sql'
'scripts_sql\drop_trigger_proc.sql'

ambas estão com erros
