### ISSUE TITLE
Funções do sistema (Falta Implementar)

### ISSUE THREAD

**Issue by ribarski** [taylorteixeira/projeto-bd-odontologico#5]
Cadastro de Pacientes: Permitir o cadastro de novos pacientes, incluindo informações como nome, data de nascimento, sexo, endereço, telefone e email.

Cadastro de Dentistas: Semelhante ao cadastro de pacientes, este recurso permitiria adicionar novos dentistas, incluindo nome, CRO (registro de cirurgião-dentista), especialidade, telefone e email.

Agendamento de Consultas: Os usuários podem marcar consultas, selecionando um paciente, um dentista, uma data e hora, e fornecendo um motivo para a consulta.

Registro de Tratamentos: Após uma consulta, os tratamentos realizados podem ser registrados, incluindo uma descrição do tratamento e seu custo.

Geração de Prontuários: Os prontuários podem ser gerados para registrar detalhes sobre consultas, incluindo o paciente, dentista, data, diagnóstico, tratamento realizado e observações adicionais.

Registro de Pagamentos: Este recurso permite registrar pagamentos feitos pelos pacientes, incluindo o valor, data do pagamento, e o método de pagamento.

Gerenciamento de Agenda: Permite visualizar e gerenciar a agenda dos dentistas, marcando horários disponíveis e indisponíveis.

Emissão de Receitas: Os dentistas podem emitir receitas para os pacientes, registrando o valor, data da receita e uma descrição do medicamento prescrito.

**Comment by miguelfermo** [comment]
Sistema possível -  Funções

1- Login:
----|_ Funções - Paciente
------|_ Menu Pacientes
---------|_ Gerenciamento de Agenda (Adicionar, Excluir, Editar e Listar)
------------|_ Agendamento Consulta
------------|_ Exclusão Consulta
------------|_ Edição data da Consulta
------------|_ Listagem Consultas Pendentes
---------|_ Dentistas disponíveis (Listar)
---------|_ Histórico de Pagamentos (Listar)
---------|_ Visualização de Receitas de medicamentos (Listar)

----|_ Funções - Dentista
------|_ Menu Dentista
---------|_ Gerenciamento de Agenda (Adicionar, Excluir, Editar e Listar)
------------|_ Agendamento Consulta
------------|_ Exclusão Consulta
------------|_ Edição data da Consulta
------------|_ Listagem Consultas Pendentes
---------|_ Gerenciamento de Pacientes (Listar) 
---------|_ Gerenciamento de Dentistas (Listar)
---------|_ Gerenciamento de Tratamentos (Listar)

2- Cadastro:
----|_ Funções - Pacientes
------|_ Menu Pacientes
---------|_ Gerenciamento de Agenda (Adicionar, Excluir, Editar e Listar)
------------|_ Agendamento Consulta
------------|_ Exclusão Consulta
------------|_ Edição data da Consulta
------------|_ Listagem Consultas Pendentes
---------|_ Dentistas disponíveis (Listar)
---------|_ Histórico de Pagamentos (Listar)
---------|_ Visualização de Receitas de medicamentos (Listar)

3- Sair

**Comment by miguelfermo** [comment]
Sistema possível -  Funções

1- Login (Para identificação de rotina de um Dentista): 

----|_ Funções - Dentista
------|_ Menu Dentista
---------|_ Gerenciamento de Agenda (Adicionar, Excluir, Editar e Listar)
------------|_ Agendamento Consulta
------------|_ Exclusão Consulta
------------|_ Edição data da Consulta
------------|_ Listagem Consultas Pendentes

2- Sair
