### ISSUE TITLE
Perguntas - Index (4 Perguntas necessárias)

### ISSUE THREAD

**Issue by CauaLoch9860** [taylorteixeira/projeto-bd-odontologico#9]
1. Total de receitas por dentista em um determinado período, incluindo número de consultas e custo total dos tratamentos realizados.
WITH ConsultaDetalhes AS (
    SELECT 
        c.DentistaID,
        COUNT(c.ConsultaID) AS NumeroDeConsultas,
        SUM(t.Custo) AS CustoTotalTratamentos,
        SUM(r.Valor) AS ReceitaTotal
    FROM 
        Consultas c
    LEFT JOIN 
        Prontuarios p ON c.PacienteID = p.PacienteID AND c.DentistaID = p.DentistaID AND c.DataHora = p.Data
    LEFT JOIN 
        Tratamentos t ON p.TratamentoID = t.TratamentoID
    LEFT JOIN 
        Receitas r ON c.PacienteID = r.PacienteID AND CAST(c.DataHora AS DATE) = r.DataReceita
    WHERE 
        c.DataHora BETWEEN '2024-06-01' AND '2024-06-30'
    GROUP BY 
        c.DentistaID
)
SELECT 
    d.Nome AS Dentista,
    cd.NumeroDeConsultas,
    cd.CustoTotalTratamentos,
    cd.ReceitaTotal
FROM 
    Dentistas d
INNER JOIN 
    ConsultaDetalhes cd ON d.DentistaID = cd.DentistaID
ORDER BY 
    cd.ReceitaTotal DESC;

2. Pacientes que mais gastaram em tratamentos nos últimos três meses, incluindo detalhes do tratamento e o dentista responsável.
WITH GastosPacientes AS (
    SELECT 
        r.PacienteID,
        SUM(r.Valor) AS GastoTotal
    FROM 
        Receitas r
    WHERE 
        r.DataReceita BETWEEN DATEADD(MONTH, -3, GETDATE()) AND GETDATE()
    GROUP BY 
        r.PacienteID
)
SELECT 
    p.Nome AS Paciente,
    gp.GastoTotal,
    t.Descricao AS Tratamento,
    d.Nome AS Dentista,
    pr.Data
FROM 
    GastosPacientes gp
INNER JOIN 
    Pacientes p ON gp.PacienteID = p.PacienteID
INNER JOIN 
    Prontuarios pr ON p.PacienteID = pr.PacienteID
INNER JOIN 
    Tratamentos t ON pr.TratamentoID = t.TratamentoID
INNER JOIN 
    Dentistas d ON pr.DentistaID = d.DentistaID
WHERE 
    pr.Data BETWEEN DATEADD(MONTH, -3, GETDATE()) AND GETDATE()
ORDER BY 
    gp.GastoTotal DESC;

3. Média de custo dos tratamentos por especialidade dos dentistas, considerando apenas os tratamentos realizados no último ano.
SELECT 
    d.Especialidade,
    AVG(t.Custo) AS MediaCustoTratamento
FROM 
    Dentistas d
INNER JOIN 
    Prontuarios p ON d.DentistaID = p.DentistaID
INNER JOIN 
    Tratamentos t ON p.TratamentoID = t.TratamentoID
WHERE 
    p.Data BETWEEN DATEADD(YEAR, -1, GETDATE()) AND GETDATE()
GROUP BY 
    d.Especialidade
ORDER BY 
    MediaCustoTratamento DESC;

4. Pacientes atendidos por cada dentista, divididos por sexo, nos últimos seis meses.
SELECT 
    d.Nome AS Dentista,
    p.Sexo,
    COUNT(c.ConsultaID) AS NumeroDePacientes
FROM 
    Consultas c
INNER JOIN 
    Pacientes p ON c.PacienteID = p.PacienteID
INNER JOIN 
    Dentistas d ON c.DentistaID = d.DentistaID
WHERE 
    c.DataHora BETWEEN DATEADD(MONTH, -6, GETDATE()) AND GETDATE()
GROUP BY 
    d.Nome, p.Sexo
ORDER BY 
    d.Nome, p.Sexo;

5. Taxa de ocupação dos dentistas em termos de consultas agendadas versus disponibilidades em um determinado mês.
WITH ConsultasAgendadas AS (
    SELECT 
        DentistaID,
        COUNT(ConsultaID) AS ConsultasAgendadas
    FROM 
        Consultas
    WHERE 
        DataHora BETWEEN '2024-06-01' AND '2024-06-30'
    GROUP BY 
        DentistaID
),
Disponibilidades AS (
    SELECT 
        DentistaID,
        COUNT(AgendaID) AS Disponibilidades
    FROM 
        Agendas
    WHERE 
        DataHora BETWEEN '2024-06-01' AND '2024-06-30'
    GROUP BY 
        DentistaID
)
SELECT 
    d.Nome AS Dentista,
    COALESCE(ca.ConsultasAgendadas, 0) AS ConsultasAgendadas,
    COALESCE(disp.Disponibilidades, 0) AS Disponibilidades,
    CASE WHEN COALESCE(disp.Disponibilidades, 0) = 0 THEN 0 
         ELSE (COALESCE(ca.ConsultasAgendadas, 0) * 100.0 / COALESCE(disp.Disponibilidades, 0))
    END AS TaxaDeOcupacao
FROM 
    Dentistas d
LEFT JOIN 
    ConsultasAgendadas ca ON d.DentistaID = ca.DentistaID
LEFT JOIN 
    Disponibilidades disp ON d.DentistaID = disp.DentistaID
ORDER BY 
    TaxaDeOcupacao DESC;

**Comment by miguelfermo** [comment]
devem ser perguntas super especificas e não tão abrangentes, como 'quem consultou dia XX e pagou XXX' e possívelmente em tal horário, ao invés de perguntas como 'quais os clientes que tem idade acima de 50 anos?'
